---
- name: Setup raspberry pi
  hosts: all
  gather_facts: true

  roles:
  - {role: rpi_base}
  - {role: ir, gpio_in_pin: 15, gpio_out_pin: 14}
  - {role: photo_sensor}
  - {role: docker}
  - {
      role: ac,
      AC_LOCATION: 3rd,
      AWS_ACCESS_KEY_ID: x,
      AWS_SECRET_ACCESS_KEY: x,
      SLACK_TOKEN: x,
      SLACK_URL: "http://yourdomain.com",
     }

